version: '3.4'

services:
  flask-app:
    container_name: flask-compose
    image: flask:0.0.6
    build:
      context: ./flask-backend
      dockerfile: dockerfile
    restart: always
    ports:
      - "5010:5000"
    depends_on:
      - postgres

  postgres:
    container_name: postgres-compose
    image: postgres:12
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=rangris123
      - POSTGRES_PASSWORD=poseidon
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  frontend:
    image: frontend:latest
    build:
      context: ./vue-forntend
      dockerfile: dockerfile
    ports:
      - 8090:8080
    depends_on:
      - flask-app

volumes:
  postgres-data:
