name: CI (Continuous Integration)

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build-testing:
    name: BuildnTest
    runs-on: windows-latest

    steps:
      - name: Check repository
        uses: actions/checkout@v2
    
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      
      - name: BuildRun Container
        run: |
          sudo docker compose up -d

      - name: Requirements install
        run: |
          pip install -r testing\requirements.txt

      - name: Test
        run: |
          sleep 20
          pytest testing/test.py          
